name: CI

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build-and-test:
    # Задаём матрицу тестирования
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    
    # Указываем раннер из матрицы
    runs-on: ${{ matrix.os }}
    name: Build & Test on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # Настройка Buildx для кэширования образа
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Сборка образа через Buildx с кэшированием
      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          tags: mona_ci:latest
          # Выгружаем образ в обычный Docker демон, 
          # чтобы следующий шаг (docker run) его увидел
          load: true
          build-args: |
            USER_UID=1001
            USER_GID=1001
          # Изолируем кэш - добавляем scope с именем ОС
          cache-from: type=gha,scope=docker-cache-${{ matrix.os }}
          cache-to: type=gha,mode=max,scope=docker-cache-${{ matrix.os }}
          no-cache: ${{ github.event_name == 'schedule' }}

      # Выполнение скрипта тестирования внутри изолированного контейнера
      - name: Run Global CI Script inside Docker
        run: |
          mkdir -p ${{ github.workspace }}/build
          
          docker run --rm \
            -v ${{ github.workspace }}/src:/home/mona_dev/mona_ws/src \
            -v ${{ github.workspace }}/scripts:/home/mona_dev/mona_ws/scripts \
            -v ${{ github.workspace }}/configs:/home/mona_dev/mona_ws/configs \
            -v ${{ github.workspace }}/build:/home/mona_dev/mona_ws/build \
            mona_ci:latest \
            /bin/bash -c "cd /home/mona_dev/mona_ws && ./scripts/local_ci.bash"
      
      # Публикация отчётов в интерфейсе GitHub
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # Шаг должен выполниться, даже если тесты упали
        with:
          report_paths: 'build/**/test_results/**/*.xml'
          check_name: "ROS 2 Test Report (${{ matrix.os }})"
      
      # Загрузка отчёта о покрытии в Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.info
          flags: ${{ matrix.os }}
          fail_ci_if_error: false
